name: Generate Emulators

on:
  schedule:
    - cron: "0 */2 * * *"   # runs every 2 hours
  workflow_dispatch:         # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run generator
        run: node generateTools.js
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_API }}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto update emulators" || echo "No changes"
          git push https://x-access-token:${{ secrets.MY_GITHUB_API }}@github.com/ZAGv2/Emulators.git HEAD:main
